FROM ghcr.io/compbiocore/lee_rnaseq:apr_26_01-36-57_2024

BiocManager::install("airway")
BiocManager::install("AnnotationHub")
BiocManager::install("enrichplot")
BiocManager::install("biomaRt")
BiocManager::install("DESeq2")
BiocManager::install("GenomicFeatures")
BiocManager::install("BSgenome")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
BiocManager::install("clusterProfiler")
