FROM ghcr.io/compbiocore/ccv_bootcamp_annotations:jun_10_03-32-17_2024
RUN R -e "BiocManager::install(c('AnnotationHub', 'enrichplot', 'biomaRt', 'GenomicFeatures', 'BSgenome', 'BSgenome.Hsapiens.UCSC.hg19', 'clusterProfiler'))"
